// src/layouts/components/TagsView.vue
<template>
  <div class="tags-view">
    <ADropdown
      v-for="tag in tags"
      :key="tag.fullPath"
      class="route-tag-dropdown"
      trigger="contextMenu"
    >
      <ATag
        :closable="canCloseTag(tag)"
        :class="['route-tag', { 'is-active': tag.fullPath === route.fullPath }]"
        @click="openTag(tag)"
        @close="closeTag(tag)"
      >
        <Icon v-if="tag.icon" class="route-tag-icon" :icon="tag.icon" />
        <span>{{ tag.title }}</span>
      </ATag>

      <template #content>
        <ADoption :disabled="!canCloseTag(tag)" @click="closeTag(tag)">
          <span class="tag-menu-option">
            <Icon class="tag-menu-icon" icon="ri:close-circle-line" />
            <span>关闭当前</span>
          </span>
        </ADoption>
        <ADoption :disabled="tags.length <= 1" @click="closeOtherTags(tag)">
          <span class="tag-menu-option">
            <Icon class="tag-menu-icon" icon="ri:close-line" />
            <span>关闭其他</span>
          </span>
        </ADoption>
        <ADoption :disabled="!hasClosableLeft(tag)" @click="closeLeftTags(tag)">
          <span class="tag-menu-option">
            <Icon class="tag-menu-icon" icon="ri:skip-left-line" />
            <span>关闭左侧</span>
          </span>
        </ADoption>
        <ADoption
          :disabled="!hasClosableRight(tag)"
          @click="closeRightTags(tag)"
        >
          <span class="tag-menu-option">
            <Icon class="tag-menu-icon" icon="ri:skip-right-line" />
            <span>关闭右侧</span>
          </span>
        </ADoption>
      </template>
    </ADropdown>
  </div>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref, watch } from "vue";
import { useRoute, useRouter } from "vue-router";
import { ROUTE_PATHS } from "../../router/paths";
import {
  getRouteIcon,
  getRouteTitle,
  ROUTE_ICONS,
  ROUTE_TITLES,
} from "../menu";

const route = useRoute();
const router = useRouter();
const homePath = ROUTE_PATHS.home.index;
const tags = ref([createStaticTag(homePath)]);

const currentTag = computed(() => ({
  fullPath: route.fullPath,
  icon: getRouteIcon(route),
  path: route.path,
  title: getRouteTitle(route),
}));

watch(
  currentTag,
  (tag) => {
    if (!route.meta.requiresAuth) {
      return;
    }

    if (!tags.value.some((item) => item.fullPath === tag.fullPath)) {
      tags.value.push(tag);
    }
  },
  { immediate: true },
);

function createStaticTag(path) {
  return {
    fullPath: path,
    icon: ROUTE_ICONS[path] || "ri:file-list-line",
    path,
    title: ROUTE_TITLES[path] || "未命名页面",
  };
}

function canCloseTag(tag) {
  return tag.path !== homePath && tags.value.length > 1;
}

function openTag(tag) {
  if (tag.fullPath !== route.fullPath) {
    router.push(tag.fullPath);
  }
}

function closeTag(tag) {
  if (!canCloseTag(tag)) {
    return;
  }

  const index = tags.value.findIndex((item) => item.fullPath === tag.fullPath);

  if (index === -1) {
    return;
  }

  tags.value.splice(index, 1);

  if (tag.fullPath !== route.fullPath) {
    return;
  }

  const nextTag = tags.value[index - 1] ||
    tags.value[index] || {
      fullPath: homePath,
    };
  router.push(nextTag.fullPath);
}

function removeTagByFullPath(fullPath) {
  const index = tags.value.findIndex((item) => item.fullPath === fullPath);

  if (index === -1 || !canCloseTag(tags.value[index])) {
    return;
  }

  tags.value.splice(index, 1);
}

function handleCloseCurrentRouteTag(event) {
  removeTagByFullPath(event.detail?.fullPath || route.fullPath);
}

onMounted(() => {
  window.addEventListener("close-current-route-tag", handleCloseCurrentRouteTag);
});

onBeforeUnmount(() => {
  window.removeEventListener(
    "close-current-route-tag",
    handleCloseCurrentRouteTag,
  );
});

function normalizeTags(nextTags) {
  const homeTag =
    tags.value.find((item) => item.path === homePath) ||
    createStaticTag(homePath);
  const merged = [
    homeTag,
    ...nextTags.filter((item) => item.path !== homePath),
  ];
  const seen = new Set();

  return merged.filter((item) => {
    if (seen.has(item.fullPath)) {
      return false;
    }

    seen.add(item.fullPath);
    return true;
  });
}

function applyTags(nextTags, fallbackTag) {
  tags.value = normalizeTags(nextTags);

  if (!tags.value.some((item) => item.fullPath === route.fullPath)) {
    router.push(fallbackTag?.fullPath || homePath);
  }
}

function closeOtherTags(tag) {
  applyTags([tag], tag);
}

function closeLeftTags(tag) {
  const index = tags.value.findIndex((item) => item.fullPath === tag.fullPath);

  if (index === -1) {
    return;
  }

  applyTags(
    tags.value.filter((item, itemIndex) => itemIndex >= index),
    tag,
  );
}

function closeRightTags(tag) {
  const index = tags.value.findIndex((item) => item.fullPath === tag.fullPath);

  if (index === -1) {
    return;
  }

  applyTags(
    tags.value.filter((item, itemIndex) => itemIndex <= index),
    tag,
  );
}

function hasClosableLeft(tag) {
  const index = tags.value.findIndex((item) => item.fullPath === tag.fullPath);

  return tags.value.some(
    (item, itemIndex) => itemIndex < index && canCloseTag(item),
  );
}

function hasClosableRight(tag) {
  const index = tags.value.findIndex((item) => item.fullPath === tag.fullPath);

  return tags.value.some(
    (item, itemIndex) => itemIndex > index && canCloseTag(item),
  );
}
</script>

<style lang="scss" scoped>
.tags-view {
  height: 44px;
  padding: 8px 12px 0;
  box-sizing: border-box;
  background: #dee1e6;
  border-bottom: 1px solid #ffffff;
  display: flex;
  align-items: flex-end;
  gap: 4px;
  overflow-x: auto;
  overflow-y: hidden;
}

.tags-view::-webkit-scrollbar {
  height: 3px;
}

.tags-view::-webkit-scrollbar-thumb {
  background: #c1c5ce;
  border-radius: 2px;
}

.tags-view::-webkit-scrollbar-track {
  background: transparent;
}

.route-tag-dropdown {
  flex: none;
  height: 36px;
}

.route-tag {
  flex: none;
  cursor: pointer;
  user-select: none;
  height: 36px !important;
  line-height: 36px !important;
  background-color: transparent !important;
  border: none !important;
  border-radius: 8px 8px 0 0 !important;
  padding: 0 16px !important;
  color: #5f6368 !important;
  transition: all 0.2s ease;
  font-size: 13px;
  display: inline-flex;
  align-items: center;

  &:hover:not(.is-active) {
    background-color: #f1f3f4 !important;
  }

  &.is-active {
    background-color: #ffffff !important;
    color: #1a73e8 !important;
    font-weight: 500;
    box-shadow: 0 -2px 6px rgba(0, 0, 0, 0.04);
    z-index: 1;
  }

  :deep(.arco-tag-content) {
    display: inline-flex;
    align-items: center;
    gap: 6px;
  }

  :deep(.arco-tag-close-btn) {
    color: #5f6368 !important;
    margin-left: 8px !important;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 16px;
    height: 16px;
    border-radius: 50%;
    transition: background-color 0.2s;

    &:hover {
      background-color: rgba(0, 0, 0, 0.08) !important;
    }
  }

  &.is-active :deep(.arco-tag-close-btn) {
    color: #1a73e8 !important;

    &:hover {
      background-color: rgba(26, 115, 232, 0.1) !important;
    }
  }
}

.route-tag-icon {
  width: 14px;
  height: 14px;
  flex: none;
}

.tag-menu-option {
  display: inline-flex;
  align-items: center;
  gap: 7px;
}

.tag-menu-icon {
  width: 15px;
  height: 15px;
  flex: none;
}
</style>

// src/layouts/components/TagsView.tsx
import { Dropdown } from "antd";
import { Icon } from "@iconify/react";
import { useEffect, useMemo, useState } from "react";
import { Link, useLocation, useNavigate } from "react-router-dom";
import {
  getActiveMenuPath,
  routeIcons,
  routeTitles,
} from "../menu";

type RouteTag = {
  fullPath: string;
  icon: string;
  path: string;
  title: string;
};

const homePath = "/dashboard";

function createRouteTag(fullPath: string, pathname: string): RouteTag {
  const path = getActiveMenuPath(pathname);

  return {
    fullPath,
    icon: routeIcons[path] || "ri:file-list-line",
    path,
    title: routeTitles[path] || "未命名页面",
  };
}

function createHomeTag(): RouteTag {
  return createRouteTag(homePath, homePath);
}

function normalizeTags(tags: RouteTag[]): RouteTag[] {
  const homeTag = tags.find((item) => item.path === homePath) || createHomeTag();
  const seen = new Set<string>();

  return [homeTag, ...tags.filter((item) => item.path !== homePath)].filter(
    (item) => {
      if (seen.has(item.fullPath)) {
        return false;
      }

      seen.add(item.fullPath);
      return true;
    },
  );
}

export function TagsView() {
  const location = useLocation();
  const navigate = useNavigate();
  const activeFullPath = `${location.pathname}${location.search}${location.hash}`;
  const currentTag = useMemo(
    () => createRouteTag(activeFullPath, location.pathname),
    [activeFullPath, location.pathname],
  );
  const [tags, setTags] = useState<RouteTag[]>([createHomeTag()]);

  function canCloseTag(tag: RouteTag, tagList = tags): boolean {
    return tag.path !== homePath && tagList.length > 1;
  }

  function applyTags(nextTags: RouteTag[], fallbackTag?: RouteTag) {
    const normalized = normalizeTags(nextTags);

    setTags(normalized);

    if (!normalized.some((item) => item.fullPath === activeFullPath)) {
      navigate(fallbackTag?.fullPath || homePath);
    }
  }

  function closeTag(tag: RouteTag) {
    if (!canCloseTag(tag)) {
      return;
    }

    const index = tags.findIndex((item) => item.fullPath === tag.fullPath);

    if (index === -1) {
      return;
    }

    const nextTags = tags.filter((item) => item.fullPath !== tag.fullPath);
    setTags(nextTags);

    if (tag.fullPath !== activeFullPath) {
      return;
    }

    const nextTag = nextTags[index - 1] || nextTags[index] || createHomeTag();
    navigate(nextTag.fullPath);
  }

  function closeOtherTags(tag: RouteTag) {
    applyTags([tag], tag);
  }

  function closeLeftTags(tag: RouteTag) {
    const index = tags.findIndex((item) => item.fullPath === tag.fullPath);

    if (index === -1) {
      return;
    }

    applyTags(
      tags.filter((item, itemIndex) => itemIndex >= index),
      tag,
    );
  }

  function closeRightTags(tag: RouteTag) {
    const index = tags.findIndex((item) => item.fullPath === tag.fullPath);

    if (index === -1) {
      return;
    }

    applyTags(
      tags.filter((item, itemIndex) => itemIndex <= index),
      tag,
    );
  }

  function hasClosableLeft(tag: RouteTag): boolean {
    const index = tags.findIndex((item) => item.fullPath === tag.fullPath);

    return tags.some(
      (item, itemIndex) => itemIndex < index && canCloseTag(item),
    );
  }

  function hasClosableRight(tag: RouteTag): boolean {
    const index = tags.findIndex((item) => item.fullPath === tag.fullPath);

    return tags.some(
      (item, itemIndex) => itemIndex > index && canCloseTag(item),
    );
  }

  useEffect(() => {
    setTags((tagList) =>
      tagList.some((item) => item.fullPath === currentTag.fullPath)
        ? tagList
        : [...tagList, currentTag],
    );
  }, [currentTag]);

  useEffect(() => {
    function handleCloseCurrentRouteTag(event: Event) {
      const detail = (event as CustomEvent<{ fullPath?: string }>).detail;
      const targetFullPath = detail?.fullPath || activeFullPath;

      setTags((tagList) => {
        const index = tagList.findIndex(
          (item) => item.fullPath === targetFullPath,
        );
        const tag = tagList[index];

        if (!tag || !canCloseTag(tag, tagList)) {
          return tagList;
        }

        const nextTags = tagList.filter(
          (item) => item.fullPath !== targetFullPath,
        );

        if (targetFullPath === activeFullPath) {
          const nextTag = nextTags[index - 1] || nextTags[index] || createHomeTag();
          navigate(nextTag.fullPath);
        }

        return nextTags;
      });
    }

    window.addEventListener("close-current-route-tag", handleCloseCurrentRouteTag);

    return () => {
      window.removeEventListener(
        "close-current-route-tag",
        handleCloseCurrentRouteTag,
      );
    };
  }, [activeFullPath, navigate]);

  return (
    <div className="react-tags-view">
      {tags.map((tag) => (
        <Dropdown
          key={tag.fullPath}
          menu={{
            items: [
              {
                disabled: !canCloseTag(tag),
                icon: <Icon icon="ri:close-circle-line" />,
                key: "close",
                label: "关闭当前",
              },
              {
                disabled: tags.length <= 1,
                icon: <Icon icon="ri:close-line" />,
                key: "closeOther",
                label: "关闭其他",
              },
              {
                disabled: !hasClosableLeft(tag),
                icon: <Icon icon="ri:skip-left-line" />,
                key: "closeLeft",
                label: "关闭左侧",
              },
              {
                disabled: !hasClosableRight(tag),
                icon: <Icon icon="ri:skip-right-line" />,
                key: "closeRight",
                label: "关闭右侧",
              },
            ],
            onClick: ({ key }) => {
              if (key === "close") {
                closeTag(tag);
              }

              if (key === "closeOther") {
                closeOtherTags(tag);
              }

              if (key === "closeLeft") {
                closeLeftTags(tag);
              }

              if (key === "closeRight") {
                closeRightTags(tag);
              }
            },
          }}
          trigger={["contextMenu"]}
        >
          <span
            className={
              tag.fullPath === activeFullPath
                ? "react-route-tag active"
                : "react-route-tag"
            }
          >
            <Link to={tag.fullPath}>
              <Icon className="react-route-tag-icon" icon={tag.icon} />
              <span>{tag.title}</span>
            </Link>
            {canCloseTag(tag) ? (
              <button
                aria-label="关闭标签"
                className="react-route-tag-close"
                type="button"
                onClick={(event) => {
                  event.preventDefault();
                  event.stopPropagation();
                  closeTag(tag);
                }}
              >
                <Icon icon="ri:close-line" />
              </button>
            ) : null}
          </span>
        </Dropdown>
      ))}
    </div>
  );
}
